---
# Create Users with password for ssh access
- name: Create users
  hosts: All
  become: yes
  environment:
   PATH: /usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
  roles:
    - users

# Host can be specified here or a list of hosts can be specified in an inventory file and use it for execution.
